jobs:
- job: BuildBaseExe
  timeoutInMinutes: 0
  strategy:
    matrix:
      linux_amd64:
        imageName: 'ubuntu-20.04'
        arch: 'linux/amd64'
        node: '20.18.0'
        ptrcompress: false

  pool:
    vmImage: $(imageName)
  
  variables:
    myPhaseName: $(System.PhaseName)
    myPhaseDisplayName: $(System.PhaseDisplayName)

  steps:
  - script: env
    displayName: Environment
